version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy-nginx 
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  backend:
    image: nginx:latest
    container_name: backend-nginx
    expose:
      - "10010"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    expose:
      - "8080"
    ports:
      - "8080:8080"
  php:
    image: php:7.3-fpm
    container_name: php
    expose:
      - "9000"
    volumes:
      - ./source:/source
